### ISSUE TITLE
autofocus attribute not set

### ISSUE THREAD

**Issue by pke** [insin/react-maskedinput#49]
I try to force the input to take focus when its displayed like this: `<MaskedInput autoFocus={true}/>` but the control does not set the attribute.

**Comment by bpugh** [comment]
This isn't rally a MaskedInput issue since it is being passed to the underlying input component but React itself actually never renders the `autofocus` attribute since they polyfill the behavior for cross browser support.
You can read the full thread about it here: https://github.com/facebook/react/issues/3066

**Comment by pke** [comment]
Thanks! Learn something new every day.
