### ISSUE TITLE
deprecation error due to React.createClass

### ISSUE THREAD

**Issue by freaksauce** [insin/react-maskedinput#93]
React.createClass is being deprecated in React 16.0 and currently shows deprecation warnings in 15.5 

`Warning: MaskedInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

Code needs to be refactored to use `class MaskedInput extends Component` syntax.

**Comment by raygerami** [comment]
Is this fixed? It still shows in version 3.3.4.

**Comment by MichaelDeBoey** [comment]
@raygerami `v3.3.4` (the latest release of this package) is released December 16th 2016.
The warnings were [introduced](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) since April 7th 2017 together with `React v15.5`, so it's normal that it's still not in this package
Also #94 isn't merged yet so...

**Comment by raygerami** [comment]
@MichaelDeBoey thanks

**Comment by freaksauce** [comment]
I've tried contacting the dev a couple of times and no response unfortunately

**Comment by MichaelDeBoey** [comment]
@insin I think we're all waiting for this one. 😕
Please merge #94! 🙂

**Comment by armsteadj1** [comment]
https://github.com/sanniassin/react-input-mask
